import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { config } from '@fortawesome/fontawesome-svg-core'; 
import '@fortawesome/fontawesome-svg-core/styles.css'; 
config.autoAddCss = false; 

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "UI-Twinkga",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
